/* 任务与级别数据：LEVELS / TASKS / 技能徽章 / 语速 */
const LEVEL_ORDER = ["A1", "A2", "B1", "B2", "C1", "C2"];
const LEVELS = {
  A1: { label: "A1 入门",  desc: "能写简单句子，介绍自己、日常物品", words: 15,  secs: 60 },
  A2: { label: "A2 基础",  desc: "能讲过去的事、写简单邮件和回复", words: 30,  secs: 90 },
  B1: { label: "B1 进阶",  desc: "能表达观点、描述经历、处理日常沟通", words: 50,  secs: 120 },
  B2: { label: "B2 独立",  desc: "能有理有据地争论、写工作邮件", words: 80,  secs: 150 },
  C1: { label: "C1 流利",  desc: "能即兴演讲、写有说服力的长文", words: 120, secs: 180 },
  C2: { label: "C2 精通",  desc: "能玩转风格、幽默和精准辨析", words: 150, secs: 180 },
};

const TASKS = {
  A1: [
    { t: "写", cn: "用英语写 3 句自我介绍：名字、城市、一个爱好", en: "Introduce yourself in 3 sentences: name, city, one hobby." },
    { t: "听", cn: "听两遍（不看原文），说出或写下 Anna 早上做的三件事", en: "Listen twice without reading. What three things does Anna do in the morning?",
      passage: "Hi, I'm Anna. I live in Beijing. Every morning I get up at seven. I drink coffee and eat bread. Then I go to work by bus." },
    { t: "说", cn: "看着你的桌子，大声说出 5 样东西：There is a ...", en: "Look at your desk. Say 5 things out loud: 'There is a ...'" },
    { t: "读", cn: "读这封便条，然后用英语说出或写下：什么时候、在哪里、带什么", en: "Read the note, then say or write: when, where, and what to bring.",
      passage: "Dear Tom, the meeting is at 3 pm on Friday, in Room 202. Please bring your laptop. See you there. — Lisa" },
    { t: "写", cn: "你今天吃了什么？写下来（可以配表情吐槽）", en: "What did you eat today? Write it down." },
    { t: "听", cn: "听两遍，记下店里三种水果和苹果的价格", en: "Listen twice. Write down the three fruits and the price of apples.",
      passage: "Welcome to my shop. We have apples, bananas, and oranges. The apples are red and sweet. One kilo of apples is five yuan." },
    { t: "说", cn: "描述今天的天气和你穿的衣服", en: "Describe today's weather and what you are wearing." },
    { t: "读", cn: "读完这段自我介绍，仿照它写或说两句关于你自己", en: "Read this self-introduction, then say two similar sentences about yourself.",
      passage: "My name is Marco. I am from Italy. I am a teacher. I like music and football. On Sundays I play football with my friends." },
    { t: "写", cn: "给家人或朋友发一条英文消息，真的发出去", en: "Send a real English message to a friend or family member." },
    { t: "听", cn: "听两遍：今天天气怎么样？明天呢？说话人打算怎么办？", en: "Listen twice. How is the weather today and tomorrow? What will the speaker do?",
      passage: "Today is Monday. It is sunny and hot. I wear a T-shirt and shorts. But tomorrow it will rain, so I will take an umbrella." },
    { t: "说", cn: "说出你一天的时间表：I get up at ...", en: "Say your daily schedule out loud." },
    { t: "读", cn: "读这份咖啡店菜单，用英语点一单：你要什么、一共多少钱", en: "Read the menu, then order in English: what do you want and how much is it?",
      passage: "Welcome to Sun Cafe. Coffee is three dollars. Tea is two dollars. We also have cakes. The chocolate cake is four dollars. It is very popular." },
    { t: "写", cn: "用英语写 3 句：你喜欢什么颜色、为什么", en: "Write 3 sentences: what colors you like and why." },
    { t: "听", cn: "听两遍，说出 Ben 家里有几个人、有没有宠物", en: "Listen twice. How many people are in Ben's family? Does he have a pet?",
      passage: "My name is Ben. I live with my mother and my father. I have no brothers or sisters. We have a small dog. His name is Max." },
    { t: "说", cn: "说出 5 件你房间里有的东西：There is a ... in my room", en: "Say 5 things in your room: 'There is a ... in my room'." },
    { t: "读", cn: "读这条短信，说出或写下：Tom 约了什么时间、在哪里、要带什么", en: "Read the text. When, where, and what to bring?",
      passage: "Hi Jack, the football game is on Sunday at four, in the park. Bring a ball. See you there! — Tom" },
    { t: "写", cn: "写下今天的心情，用 happy / tired / hungry 中的一个词", en: "Write about how you feel today, using one of: happy / tired / hungry." },
    { t: "听", cn: "听两遍：老师几点到学校？她怎么去？", en: "Listen twice. What time does the teacher arrive? How does she get there?",
      passage: "I am a teacher. I get up at six. I go to school at seven thirty by bike. My school is near my home." },
    { t: "说", cn: "用英语介绍你的一个家人：名字、年龄、喜欢什么", en: "Introduce one family member in English: name, age, what they like." },
    { t: "读", cn: "读这个简短的自我介绍，仿照写两句关于你朋友", en: "Read it, then write two similar sentences about your friend.",
      passage: "My friend is Lily. She is from China. She is a student. She likes reading and music." },
  ],
  A2: [
    { t: "写", cn: "昨天你做了什么？写 4-5 句（过去式）", en: "What did you do yesterday? 4-5 sentences, past tense." },
    { t: "听", cn: "听两遍留言：电影几点开始？几点见面？还要带什么？", en: "Listen twice. When does the movie start? When do they meet? What should Sam bring?",
      passage: "Hi Sam, it's me. About tomorrow — the movie starts at eight, not seven. Let's meet at the cinema at seven forty-five. Oh, and bring a jacket, it will be cold." },
    { t: "说", cn: "讲一部你看过的电影或剧：讲了什么、你喜不喜欢", en: "Talk about a movie or show you watched." },
    { t: "读", cn: "读这封邀请邮件，然后写或说一条回复：去还是不去，为什么", en: "Read the invitation, then reply: will you go or not, and why?",
      passage: "Hi everyone, I'm having a birthday dinner this Saturday at 7 pm at Green Garden Restaurant. Please tell me before Thursday if you can come. — Mia" },
    { t: "写", cn: "给朋友写封邮件，推荐一家你去过的餐厅", en: "Write an email recommending a restaurant to a friend." },
    { t: "听", cn: "听两遍指路，不看原文复述：先怎么走、在哪转弯、邮局在哪", en: "Listen twice, then repeat the route without reading.",
      passage: "Go straight for two minutes, then turn left at the bank. The post office is on your right, next to a small park." },
    { t: "说", cn: "比较两个季节或两个你住过的地方，哪个更好", en: "Compare two seasons or two places you lived in." },
    { t: "读", cn: "读这条差评：一句话总结她为什么不满，再写一句你会问卖家的问题", en: "Read the review: why is she unhappy? What would you ask the seller?",
      passage: "I bought this bag last month. It looks nice and it is cheap. But after two weeks, the handle broke. I don't think I will buy from this brand again." },
    { t: "写", cn: "回复一条邀请：接受或礼貌拒绝（编一个也行）", en: "Reply to an invitation: accept or politely decline." },
    { t: "听", cn: "听两遍周末计划：周六上午、下午、周日分别做什么？", en: "Listen twice. What happens Saturday morning, afternoon, and Sunday?",
      passage: "This weekend I want to try something new. On Saturday morning I will take a cooking class. In the afternoon, I'm going to visit my grandmother. Sunday is for rest — maybe a long walk by the river." },
    { t: "说", cn: "描述你每天上班/上学的路线", en: "Describe your daily commute route." },
    { t: "读", cn: "读这个做法，然后用英语说出制作冷萃咖啡的三个步骤", en: "Read it, then say the three steps of making cold brew in English.",
      passage: "To make cold brew coffee, put fifty grams of ground coffee in a jar. Add five hundred milliliters of cold water. Wait twelve hours in the fridge. Then filter it and enjoy." },
    { t: "写", cn: "写 4-5 句：你上周末做了什么（过去式）", en: "What did you do last weekend? 4-5 sentences, past tense." },
    { t: "听", cn: "听两遍：他们为什么改时间？新的见面时间是什么？", en: "Listen twice. Why did they change the time? When do they meet now?",
      passage: "Hi Amy, sorry, I can't make it at six. My class ends at half past six. Can we meet at seven at the cafe near the station? Text me back." },
    { t: "说", cn: "比较你喜欢的两家餐厅，哪个更好、为什么", en: "Compare two restaurants you like: which is better and why." },
    { t: "读", cn: "读这条通知：什么时候停电？停电多久？为什么？", en: "Read the notice. When is the power cut? How long? Why?",
      passage: "Please note: there will be a power cut this Saturday from 9 am to 3 pm. This is because of repair work on the main line. We are sorry for the trouble." },
    { t: "写", cn: "写封邮件邀请朋友周末一起看电影", en: "Write an email inviting a friend to a movie this weekend." },
    { t: "听", cn: "听两遍天气预报：明天早上、下午分别什么天气？", en: "Listen twice. What's the weather tomorrow morning and afternoon?",
      passage: "Tomorrow will start sunny, but it will get cloudy in the afternoon. There may be some rain at night, so take an umbrella if you go out late." },
    { t: "说", cn: "描述你最近一次旅行：去了哪、做了什么", en: "Describe your most recent trip: where you went and what you did." },
    { t: "读", cn: "读这封邮件，写一句回复问一个细节", en: "Read the email, then reply asking about one detail.",
      passage: "Dear all, the office party is on Friday at 6 pm in the meeting room. Food and drinks are provided. Please bring a small gift for the gift exchange. — Anna" },
  ],
  B1: [
    { t: "写", cn: "今天发生的一件有意思（或离谱）的事", en: "Write about one interesting thing that happened today." },
    { t: "听", cn: "听两遍：他遇到了什么问题？他还没做什么？听完给出你的一条建议", en: "Listen twice. What is his problem? What hasn't he done yet? Then give one piece of advice.",
      passage: "I'm a bit stressed this week. My manager gave me a big project on Monday, and the deadline is Friday. The problem is, two people from my team are on holiday, so I have to do everything myself. I haven't told my manager yet." },
    { t: "说", cn: "你怎么看远程办公？说 2 分钟你的真实想法", en: "Your honest take on remote work, 2 minutes." },
    { t: "读", cn: "读这段谈习惯的短文：一句话总结作者观点，再说一个你同不同意的理由", en: "Summarize the author's point in one sentence, then say if you agree.",
      passage: "Most people fail to build habits because they start too big. They decide to run five kilometers every day, and quit in a week. The trick is to make the first step laughably small — one push-up, one sentence, one minute. Small steps are boring, but they survive bad days." },
    { t: "写", cn: "写一条英文动态总结这一周，可以发出去", en: "Write an English post summarizing your week." },
    { t: "听", cn: "听两遍旅行故事：手机怎么了？老人做了什么？他觉得什么最棒？", en: "Listen twice. What happened to the phone? What did the old man do? What was the best part?",
      passage: "Last summer I went to a small town in the mountains. My phone died on the first day, so I couldn't use maps. I asked an old man for directions, and he walked with me for twenty minutes, just chatting. That conversation was the best part of the whole trip." },
    { t: "说", cn: "把你专业里的一个概念讲给完全不懂的人听", en: "Explain a concept from your field to a beginner." },
    { t: "读", cn: "读这则招聘广告：这份工作哪里吸引你或不吸引你？用 2-3 句英语回应", en: "Read the job ad. What attracts or puts you off? Respond in 2-3 sentences.",
      passage: "We are looking for a part-time content writer. You will write two short articles per week about technology. You can work from anywhere. Good English is a must. Send us one article you have written." },
    { t: "写", cn: "写封邮件请假或调整会议时间", en: "Write an email asking for leave or rescheduling a meeting." },
    { t: "听", cn: "听两遍操作说明，不看原文复述完整步骤（3 步 + 在哪找到）", en: "Listen twice, then repeat the full steps without reading.",
      passage: "To save a video for offline watching, first open the video page. Then tap the three dots in the top right corner. Choose 'Save offline'. You can find all saved videos in your library, under the 'Offline' tab." },
    { t: "说", cn: "你最近做的一个决定：是什么、为什么这么定", en: "A recent decision you made and why." },
    { t: "读", cn: "读这封投诉邮件，假设你是客服，用英语写 2-3 句回复", en: "Read the complaint. You are customer service — reply in 2-3 sentences.",
      passage: "Dear customer service, I ordered a keyboard on May 3rd and it arrived yesterday, ten days late. Worse, two keys don't work. I would like a replacement or a full refund. This is the second time this has happened. — Daniel" },
    { t: "写", cn: "写一段话：你最近看的一集剧/一个视频讲了什么", en: "Write a paragraph about the latest episode or video you watched." },
    { t: "听", cn: "听两遍：她为什么换工作？新工作好在哪？", en: "Listen twice. Why did she change jobs? What's better about the new one?",
      passage: "I changed jobs last month. My old job paid well, but I worked until nine every night. Now I finish at five thirty, and I can actually cook dinner at home. Less money, but I got my evenings back." },
    { t: "说", cn: "讲讲你手机上最常用的一个 app，好在哪、坏在哪", en: "Talk about the app you use most on your phone: pros and cons." },
    { t: "读", cn: "读这段观点，一句话总结，再说一个你同意的理由", en: "Read it. Summarize in one sentence and give one reason you agree.",
      passage: "People say time is money, but time is worse than money: you can earn money back, but you can never earn a minute back. That is why wasting your own time is forgivable, but wasting someone else's time is not." },
    { t: "写", cn: "写封邮件，礼貌地催一下对方回复", en: "Write a polite email following up on a reply." },
    { t: "听", cn: "听两遍：作者建议怎么应对拖延？核心一招是什么？", en: "Listen twice. How does the speaker deal with procrastination? What's the key trick?",
      passage: "I used to wait until the last minute to start everything. Now I use a two-minute rule: if something takes less than two minutes, do it right now. It sounds small, but it stops tasks from piling up." },
    { t: "说", cn: "你同不同意「钱买不到快乐」？说 2 分钟你的看法", en: "Do you agree money can't buy happiness? 2 minutes." },
    { t: "读", cn: "读这则产品评价：他满意的点和不满意的点各是什么？", en: "Read the review. What does he like and dislike?",
      passage: "I've used this keyboard for a month. The typing feels great and the battery lasts forever — I've charged it twice. My only complaint is that it's quite loud, so I can't use it in a meeting room without feeling rude." },
  ],
  B2: [
    { t: "写", cn: "挑一个最近的热点话题，写一段你的立场", en: "Pick a trending topic and write your position on it." },
    { t: "听", cn: "听两遍：作者的核心论点是什么？你认为他低估了远程办公的哪个问题？", en: "Listen twice. What is the core argument? What problem of remote work do you think he underestimates?",
      passage: "People love to argue about remote work, but here's what the data keeps showing: it's not about where you sit, it's about how clearly the team communicates. A badly-run office is worse than a well-run remote team, and a well-run office beats a chaotic remote one. The location debate is mostly a distraction from the management problem." },
    { t: "说", cn: "辩论题：AI 会让你的工作更好还是更糟？选边站", en: "Debate: will AI make your job better or worse? Pick a side." },
    { t: "读", cn: "读这段观点：作者用婚姻比喻想说什么？写 2-3 句支持或反驳", en: "Read it. What is the marriage metaphor saying? Support or rebut in 2-3 sentences.",
      passage: "We romanticize quitting your job to travel, but most people who do it come back within a year — not because travel is bad, but because the thing they were running from is still waiting at home. A sabbatical fixes burnout the way a vacation fixes a bad marriage: temporarily, and only if nothing is actually wrong." },
    { t: "写", cn: "一个犹豫不决的朋友来信，写封建议信", en: "A friend is hesitating over a choice. Write advice." },
    { t: "听", cn: "听两遍这个故事：政策先怎样、后怎样？这个故事说明了什么？", en: "Listen twice. What happened first, then later? What does the story show?",
      passage: "A company I know banned meetings on Wednesdays. Productivity went up for a month. Then people started scheduling 'quick syncs' and 'coffee chats' on Wednesdays instead. By the third month, Wednesday was the busiest meeting day of the week. They hadn't removed meetings; they had just renamed them." },
    { t: "说", cn: "讲一次你搞砸的经历，和你学到的东西", en: "Tell a story about a failure and what you learned." },
    { t: "读", cn: "读这段季报摘要：用英语说出三个要点和团队的建议", en: "Read the report excerpt. Say the three key points and the team's suggestion in English.",
      passage: "Sales grew 12% this quarter, driven almost entirely by repeat customers. New customer growth was flat for the third quarter in a row. Marketing costs rose 8%, mostly due to higher ad prices. The team suggests shifting budget from ads to the referral program." },
    { t: "写", cn: "给一个产品写一条有理有据的差评", en: "Write a well-argued negative product review." },
    { t: "听", cn: "听两遍：短视频改变了哪三件事？作者认为它赢在哪一点？", en: "Listen twice. What three things did short video change? Why did it win, according to the speaker?",
      passage: "Short videos didn't just change entertainment; they changed how products are designed. Apps now open directly into content, search is becoming visual, and even job applications have video versions now. The format won because it removed the one thing people hate most: choosing what to do next." },
    { t: "说", cn: "向外国朋友解释一个中国习俗或网络现象", en: "Explain a Chinese custom or internet phenomenon." },
    { t: "读", cn: "读这段面试故事：为什么面试「太完美」反而是问题？你会问什么来打破局面？", en: "Read it. Why was a 'perfect' interview a problem? What would you ask instead?",
      passage: "The interview went perfectly, which was exactly the problem. Every answer came out polished and correct, and by the end, the manager realized she had learned nothing about the candidate at all — only about how well he prepared for interviews." },
    { t: "写", cn: "挑一个你不同意的流行观点，写一段反驳", en: "Pick a popular opinion you disagree with and argue against it." },
    { t: "听", cn: "听两遍：作者认为「忙碌」掩盖了什么真正的问题？", en: "Listen twice. What real problem does busyness hide, according to the speaker?",
      passage: "When someone says they're too busy, they usually mean they're too busy for you. Busy is the modern way of saying no without feeling rude. The calendar fills up not with what matters, but with what is easy to schedule." },
    { t: "说", cn: "辩论：应该先攒钱还是先花钱投资自己？选边站", en: "Debate: save money first, or spend it investing in yourself? Pick a side." },
    { t: "读", cn: "读这段论证：作者区分了哪两种「学」？你认同吗？", en: "Read it. Which two kinds of learning does he separate? Do you agree?",
      passage: "There is learning that makes you smarter, and learning that only makes you look smarter. The first feels bad in the moment, like lifting something heavy. The second feels great, like collecting stickers. Guess which one most people do at night." },
    { t: "写", cn: "写一段复盘：最近一次没做好的事，问题出在哪", en: "Write a post-mortem of something that went wrong recently." },
    { t: "听", cn: "听两遍：作者对「跟风」的态度是什么？他用什么比喻？", en: "Listen twice. What's the speaker's view on following trends, and what metaphor does he use?",
      passage: "Chasing trends is like renting your identity. The rent feels cheap at first, but you pay it every month, forever. Soon you can't remember which opinions were ever actually yours." },
    { t: "说", cn: "讲一次你坚持很久最后放弃的事，为什么放弃", en: "Tell about something you stuck with for a long time and then quit, and why." },
    { t: "读", cn: "读这段观察，用 2-3 句回应：你身边的「选择过多」例子", en: "Read it, then respond with your own example of 'too many choices'.",
      passage: "The cereal aisle has forty kinds of cereal, and somehow this makes breakfast worse. Every extra option is a tiny tax on your attention. Freedom isn't having the most choices; it's having the ones that actually matter to you." },
  ],
  C1: [
    { t: "写", cn: "就「习惯 vs 自律」写一段有立场的短评", en: "Write an opinion piece: habits vs discipline." },
    { t: "听", cn: "听两遍：作者把注意力比作什么？为什么不是钱？用自己的话复述核心观点", en: "Listen twice. What is attention compared to? Why not money? Retell the core idea in your own words.",
      passage: "We talk about attention as if it were money — something you spend. But attention is more like a lens: whatever you point it at becomes your reality. Two people can live through the same week and remember entirely different lives, simply because they noticed different things. Managing your attention isn't about productivity; it's about choosing what your life will feel like." },
    { t: "说", cn: "即兴 3 分钟：今天你脑子里出现最多的一个念头", en: "Improvise 3 minutes on today's most recurring thought." },
    { t: "读", cn: "读这段论述：作者的论证结构是什么？举一个他没想到的好例子或反例", en: "Read it. What is the argument's structure? Give one example or counterexample he missed.",
      passage: "Efficiency is a trap when applied to things that derive their value from slowness. You cannot speed-run a friendship, a child's trust, or your own understanding of a difficult book. Some things are not tasks to be completed but relationships to be inhabited, and treating them as projects is precisely what destroys them." },
    { t: "写", cn: "挑一个中文网络热梗，用英语解释给老外听", en: "Explain a Chinese internet meme in English." },
    { t: "听", cn: "听两遍：作者区分了哪两个概念？他的措辞哪里体现了克制（hedging）？", en: "Listen twice. Which two concepts does he separate? Where is his language hedged?",
      passage: "I'm not saying meetings are useless — that would be an overreaction. What I am saying is that most meetings are status updates wearing the costume of collaboration. If everyone leaves a meeting with the same information they could have read in three minutes, the meeting wasn't collaboration; it was a ritual." },
    { t: "说", cn: "复盘你最近做的一件事：什么有效、什么无效", en: "Debrief a recent project: what worked, what didn't." },
    { t: "读", cn: "读这段评测：为什么作者不推荐一部各项都优秀的手机？用英语概括这个矛盾", en: "Read it. Why won't he recommend an excellent phone? Sum up the contradiction in English.",
      passage: "The new phone is excellent in every measurable way — faster, brighter, longer-lasting. And yet I can't recommend it with enthusiasm, because excellence measured in specs has quietly become a tax on attention: every improvement arrives wrapped in one more notification, one more feed, one more reason not to look up." },
    { t: "写", cn: "为你正在做的事写一段 pitch，说服别人加入", en: "Write a pitch for something you're working on." },
    { t: "听", cn: "听两遍这个陶艺课实验：怎么设计的？结果和寓意？和你每天用英语的方法有何关系？", en: "Listen twice. How was the experiment designed? Result and moral? How does it relate to using English daily?",
      passage: "A ceramics teacher split his class in two: half would be graded on the quantity of pots they made, half on the quality of a single pot. The best pots all came from the quantity group — because while the perfectionists were theorizing, the others were learning from a mountain of imperfect pots." },
    { t: "说", cn: "讲一件你改变了看法的事，原来怎么想、现在怎么想", en: "Something you changed your mind about." },
    { t: "读", cn: "读这段评论：「watch where it pours the concrete」是什么意思？把这个逻辑用到公司或个人身上写 2-3 句", en: "Read it. What does 'watch where it pours the concrete' mean? Apply the logic to a company or a person in 2-3 sentences.",
      passage: "Every city says it wants to be walkable, and every city builds for cars. The gap between the slogan and the budget is where you find the real values. Don't listen to what a city claims to love; watch where it pours the concrete." },
    { t: "写", cn: "就「快 vs 慢」写一段有立场的短评", en: "Write an opinion piece on speed vs slowness." },
    { t: "听", cn: "听两遍：作者把「选择」比作什么？核心观点用自己的话复述", en: "Listen twice. What does he compare choice to? Retell the core point in your own words.",
      passage: "We think more choice means more freedom, but every menu, every streaming list, every swiping app is evidence of the opposite: choice is a form of work. Freedom is not having everything available; it's knowing what you don't need to consider." },
    { t: "说", cn: "即兴 3 分钟：你最近推翻的一个固有观念", en: "Improvise 3 minutes on a belief you recently overturned." },
    { t: "读", cn: "读这段文字：作者对「多任务」的讽刺点在哪？仿写一句", en: "Read it. Where's the satire on multitasking? Imitate it with one sentence.",
      passage: "We answer emails during meetings, watch shows while eating, and call this living efficiently. Multitasking is not doing many things at once; it is doing none of them with your whole self, and then wondering why nothing feels finished." },
    { t: "写", cn: "把一件复杂的事用三句话说清楚", en: "Explain something complex in exactly three sentences." },
    { t: "听", cn: "听两遍：作者如何论证「语言塑造思维」？举的是哪个例子？", en: "Listen twice. How does he argue language shapes thought? Which example?",
      passage: "Languages disagree on whether a bridge is masculine or feminine, and speakers of each will describe the same bridge with matching adjectives — sturdy or elegant. The words we inherit quietly decide what we notice. You don't think in a language; the language thinks through you a little." },
    { t: "说", cn: "用「然而」的逻辑链讲一个反直觉的结论", en: "Argue a counterintuitive conclusion using a clear 'however' chain." },
    { t: "读", cn: "读这段论述，解释「精致的平庸」是什么意思并给一个例子", en: "Read it, explain 'refined mediocrity' and give an example.",
      passage: "There is a kind of failure that is almost indistinguishable from success: the polished presentation, the well-designed report, the meeting that ends with everyone nodding. It is mediocrity wearing the costume of competence, and it is the most expensive thing a company can buy." },
  ],
  C2: [
    { t: "写", cn: "模仿你最喜欢的作家的风格写一段", en: "Write a passage imitating your favorite author's style." },
    { t: "听", cn: "听两遍：讽刺点在哪？作者用哪些细节放大荒谬？试着用英语讲给想象中的朋友", en: "Listen twice. Where is the irony? Which details amplify the absurdity? Retell it to an imaginary friend.",
      passage: "Our office is proudly paperless. We print the paperless policy every quarter and distribute it at the all-hands meeting, so everyone can hold a physical copy of our commitment to not using paper. Attendance is mandatory, and the minutes are circulated as a laminated handout." },
    { t: "说", cn: "挑一个模糊概念（如「内卷」「松弛感」）做精确辨析", en: "Dissect a fuzzy concept with precision, 3 minutes." },
    { t: "读", cn: "读这段文学性文字：幽默和伤感分别来自哪里？仿写一句你自己的 mirror 句子", en: "Read it. Where do the humor and sadness come from? Imitate it with your own 'mirror' sentence.",
      passage: "The elevator in his building had a mirror, and he had long ago made peace with the man in it — a reasonable fellow, aging at the agreed-upon rate, who nodded back with the courtesy of a colleague you pass every day but never quite meet." },
    { t: "写", cn: "写一段黑色幽默短文吐槽现代生活", en: "Write a darkly comic piece about modern life." },
    { t: "听", cn: "听两遍辩论：双方各自的立场和修辞策略？「numbers have a past」是什么意思？", en: "Listen twice. What are both positions and their rhetorical moves? What does 'numbers have a past' mean?",
      passage: "My opponent calls this a tax cut; I call it a loan from your grandchildren. He says the economy needs stimulus; I say it needs a memory of the last three times we tried this. We agree on the numbers — we simply disagree about whether numbers have a past." },
    { t: "说", cn: "同一件事，用三种方式讲：给孩子、给同事、给专家", en: "Explain one thing three ways: child, colleague, expert." },
    { t: "读", cn: "读这段论证：解释 disciplinary function 的含义，找一个生活中「给模糊定价」会改变行为的例子", en: "Read it. Explain the disciplinary function, and find a real-life example where pricing vagueness would change behavior.",
      passage: "Prediction markets are praised for aggregating information, yet their deeper function may be disciplinary: they do not make us smarter so much as they make vagueness expensive. Once a belief has a price, metaphors retire early and hedging loses its charm." },
    { t: "写", cn: "为一个你深信的观点写最强的反方论证", en: "Steel-man the opposite of something you believe." },
    { t: "听", cn: "听两遍：复述宽容悖论的论证链，把「tolerance as a border」这个比喻讲明白", en: "Listen twice. Retell the argument chain and explain the 'tolerance as a border' metaphor.",
      passage: "The paradox of tolerance states that a tolerant society must be intolerant of intolerance, or it will be consumed by it. Notice the asymmetry: tolerance is not a peace treaty between ideas, it is a peace treaty that requires enforcement — which makes it less like openness and more like a border." },
    { t: "说", cn: "把今天一个尴尬瞬间讲成一个好笑的故事", en: "Turn an awkward moment today into a funny story." },
    { t: "读", cn: "读这段讽刺：它讽刺了哪两件事的合谋？用英语解释笑点，并造一个同类句子", en: "Read it. What two things conspire here? Explain the joke in English and write a similar sentence.",
      passage: "The company announced a bold new wellness initiative: employees may now meditate for up to four minutes per day, tracked through the productivity dashboard. HR clarified that mindfulness scores will be a small but meaningful factor in year-end reviews, to ensure the practice is taken seriously." },
    { t: "写", cn: "用一个冷峻的比喻写一段关于「等待」的文字", en: "Write a passage on waiting, built around one cold, precise metaphor." },
    { t: "听", cn: "听两遍：这段话的讽刺结构是什么？笑点在哪一层？", en: "Listen twice. What's the structure of the irony, and where's the punchline?",
      passage: "Our company has a strict no-meetings Friday, which we discuss every Friday in a forty-minute meeting about protecting no-meetings Friday. The meeting is mandatory, because freedom, as everyone knows, requires supervision." },
    { t: "说", cn: "把「时间」讲给一个孩子、一个同事、一个物理学家", en: "Explain time to a child, a colleague, and a physicist." },
    { t: "读", cn: "读这段文字：幽默和悲哀分别藏在哪里？仿写你的版本", en: "Read it. Where are the humor and sadness hiding? Imitate it.",
      passage: "He had been meaning to call his father for three years, and now the number was the only thing about his father he remembered perfectly. Memory, he found, keeps the things you didn't do in sharper focus than the things you did." },
    { t: "写", cn: "为一件小事写一段庄重的讣告式幽默", en: "Write a solemn obituary for something trivial." },
    { t: "听", cn: "听两遍：复述「optimism as a duty」的论证链", en: "Listen twice. Retell the argument for 'optimism as a duty'.",
      passage: "Pessimism feels like intelligence because it asks nothing of you. Optimism is harder: it demands you act as if the better outcome is still possible, which is precisely what makes it possible. Cynicism is a couch; hope is a pair of running shoes." },
    { t: "说", cn: "即兴论证一个你自己都不太信、但能自圆其说的观点", en: "Steel-man an opinion you don't actually hold." },
    { t: "读", cn: "读这段评论，解释「friction is a feature」并给一个生活例子", en: "Read it, explain 'friction is a feature' with a real-life example.",
      passage: "Every app wants to remove friction, to make spending effortless. But friction is often the only thing standing between you and a bad decision. A two-second delay before a purchase, a password before a confession — these small walls are not bugs. They are the last honest parts of the design." },
  ],
};
// 合并外部题库（b2-reading.js），扩充 B2 阅读卡池
if (window.B2_READING && window.B2_READING.length) {
  TASKS.B2 = TASKS.B2.concat(window.B2_READING);
}

/* ============ 工具 ============ */
const $ = (sel, el = document) => el.querySelector(sel);
const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

